### ISSUE TITLE
Scripting and variables

### ISSUE THREAD

**Issue by FDrebin** [ryanblenis/MeshCentral-ScriptTask#9]
Hello, currently doing some testing with this plugin for MeshCentral so I can automate some tasks. From what I'm reading is any variable I have defined in the script I also need to define in the variables section. My question is, what is the difference between global variable and script variable? 

And aside from that, all of my scripts either have similar or the same variables, will I need to ensure every single variable is defined in the plugin, some of the scripts rely on anywhere from 10-30 variables for a single script. 

For example I have a variable called $start_time = Get-Time , will that need to be defined in the plugin variables? And if so, do I include the $ or just use start_time and then value is Get-Date ?

**Comment by ryanblenis** [comment]
Hi @FDrebin,

Any variables in your script are fine as is. The "variables" functionality of the ScriptTask within the MC web gui integration are for pulling or setting variables dynamically within your script before the script is run.

So the script could essentially look something like this:

```
$helpText = "Call #itDeptName# at #supportPhoneNumber#"

$helpText | Out-File -FilePath C:\Users\Public\Desktop\Click_For_Help.txt
```
This simply writes "Call [it dept name] at [phone number]" to a file on the desktop.
$helpText does NOT need to be defined anywhere outside your script, but you can define #itDeptName# and #supportPhoneNumber# in the ScriptTask variables section so that:

The (script level) variable #itDeptName# is "ABC Co. IT Support" (so the script always uses "ABC Co. IT Support" in place of that variable).

But say you have a client who doesn't want their employees to know the IT dept is ABC Co., and just wants it to say "Jim's Flower Shop Internal IT"... just add a variable at the mesh group level for that clients devices that #itDeptName# is "Jim's Flower Shop Internal IT" and the same script, without any changes will update it to run replacing "ABC Co. IT Support" with "Jim's Flower Shop Internal IT" for all devices within that mesh group.

Similarly, if John on Workstation1001 is always bothering you and John likes working with your IT guy Bill, you can add a node (device) level variable for #supportPhoneNumber# on Workstation1001 that uses Bill's cell phone number instead of the global variable #supportPhoneNumber# that is set to your "800-555-1212" number.

Hopefully that clears it up for you.

**Comment by FDrebin** [comment]
Ah ok awesome! So I don't need to worry about adding all the variables from all the possible scripts to this GUI, that's fantastic. Thanks so much I'm closing this out as I was getting worried of having to use a crap load of variables lol.
